version: '3.7'

services:
  bot:
    container_name: telegram-feedback-bot
    restart: always
    image: bral1488/telegram-feedback-bot:main
    volumes:
      - /etc/timezone:/etc/timezone
      - ./config.yaml:/app/config.yaml
    command: python3 -m src
